# Generated by Django 6.1.1 on 2026-10-01 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('body', models.TextField(blank=True, help_text='Markdown')),
                ('draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
