# Generated by Django 6.1.1 on 2026-09-30 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('website', 'Website'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('x', 'X'), ('bluesky', 'Bluesky'), ('mastodon', 'Mastodon'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('other', 'Other')], default='website', max_length=20)),
                ('label', models.CharField(blank=True, help_text='Shown instead of the URL', max_length=100)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='resume.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
