# Generated by Django 6.1.1 on 2026-09-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_move_links_to_socials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
